server:
  error:
    include-message: always
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Pass@123
    url: jdbc:mysql://localhost:3306/product_service
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

s2s:
  url: http://localhost:8081
